# Generated by Django 4.1 on 2022-12-07 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="author", name="sign_date",),
    ]
