# Generated by Django 4.1 on 2022-12-07 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_remove_post_author_alter_author_author"),
    ]

    operations = [
        migrations.DeleteModel(name="Author",),
        migrations.DeleteModel(name="Post",),
    ]
