# Generated by Django 4.1 on 2022-12-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blog", "0005_delete_author_delete_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("autho", models.CharField(max_length=150)),
                ("text", models.TextField()),
                ("title", models.CharField(max_length=100)),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
            ],
        ),
    ]
