# Generated by Django 4.1 on 2022-12-07 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="pub_date",),
    ]
