# Generated by Django 4.1 on 2022-12-07 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_remove_post_pub_date"),
    ]

    operations = [
        migrations.DeleteModel(name="Post",),
    ]
